import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Map, Route, Wine, Users, UserRound, Search, Plus, MapPin, Heart, ChevronRight, X, Check, Sparkles, Navigation, Share2, Store, Tag, Download, Smartphone, MoreVertical, Share} from 'lucide-react';
import {wineries,lakes} from './data/wineries';
import './styles.css';
import './enhancements.css';

const scale=[['Liked it','Nice sip'],['A glass','I’d order it'],['A bottle','Take one home'],['Multiple','Stock me up'],['Anytime','Ship it home']];
const routes={discover:'/',trip:'/trip-planner',taste:'/wine-tasting',friends:'/shared-tastings',profile:'/my-wine-journal'};
const seo={
 discover:['Explore Finger Lakes Wineries | Sips Wine Journey','Discover Finger Lakes wineries on an interactive map, compare tasting experiences, and find wines worth adding to your journey.'],
 trip:['Finger Lakes Wine Trip Planner | Sips Wine Journey','Build a Finger Lakes winery itinerary, organize stops, and share your wine journey with friends.'],
 taste:['Rate a Finger Lakes Wine Tasting | Sips Wine Journey','Rate every wine with the One Sip five-level scale and save the bottles you want to buy again.'],
 friends:['Shared Wine Tastings With Friends | Sips Wine Journey','Compare wine ratings with friends, find group favorites, and create a shareable Finger Lakes trip recap.'],
 profile:['Your Wine Journal & Tasting History | Sips Wine Journey','Save wines, wineries, tasting notes, past routes, and personalized Finger Lakes wine recommendations.']
};
function routeToTab(){const p=location.pathname;return Object.entries(routes).find(([,v])=>v===p)?.[0]||'discover'}
function setMeta(tab){const [title,description]=seo[tab];document.title=title;document.querySelector('meta[name="description"]')?.setAttribute('content',description);document.querySelector('meta[property="og:title"]')?.setAttribute('content',title);document.querySelector('meta[property="og:description"]')?.setAttribute('content',description);let c=document.querySelector('link[rel="canonical"]');if(c)c.href=`${location.origin}${routes[tab]}`;let schema=document.getElementById('page-schema');if(!schema){schema=document.createElement('script');schema.type='application/ld+json';schema.id='page-schema';document.head.appendChild(schema)}schema.textContent=JSON.stringify({'@context':'https://schema.org','@type':'WebApplication',name:'Sips — Wine Journey',url:`${location.origin}${routes[tab]}`,description,applicationCategory:'TravelApplication',operatingSystem:'Any',offers:{'@type':'Offer',price:'0',priceCurrency:'USD'},areaServed:{'@type':'Place',name:'Finger Lakes, New York'}})}

function App(){
 const [tab,setTab]=useState(routeToTab); const [selected,setSelected]=useState(null); const [trip,setTrip]=useState(()=>JSON.parse(localStorage.getItem('onesip-trip')||'[1,3]')); const [ratings,setRatings]=useState(()=>JSON.parse(localStorage.getItem('onesip-ratings')||'{}')); const [toast,setToast]=useState('');
 useEffect(()=>localStorage.setItem('onesip-trip',JSON.stringify(trip)),[trip]); useEffect(()=>localStorage.setItem('onesip-ratings',JSON.stringify(ratings)),[ratings]);
 useEffect(()=>{if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})},[]);
 useEffect(()=>{setMeta(tab);const back=()=>setTab(routeToTab());addEventListener('popstate',back);return()=>removeEventListener('popstate',back)},[tab]);
 const rated=Object.values(ratings).length; const favorites=useMemo(()=>Object.entries(ratings).filter(([,v])=>v>=4),[ratings]);
 const flash=t=>{setToast(t);setTimeout(()=>setToast(''),1800)};
 const addTrip=id=>{setTrip(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);flash(trip.includes(id)?'Removed from trip':'Added to your route')};
 const go=id=>{setTab(id);history.pushState({},'',routes[id]);scrollTo({top:0,behavior:'smooth'})};
 return <div className="shell">
  <header><button className="brand" onClick={()=>go('discover')} aria-label="Sips Wine Journey home"><span>S</span><b>SIPS <i>WINE JOURNEY</i></b></button><div className="region"><MapPin size={15}/> Finger Lakes, NY</div><button className="avatar" onClick={()=>go('profile')} aria-label="Open your wine journal">AC</button></header>
  <main>
   {tab==='discover'&&<Discover onOpen={setSelected} trip={trip} addTrip={addTrip}/>} 
   {tab==='trip'&&<Trip trip={trip} ratings={ratings} onOpen={setSelected}/>} 
   {tab==='taste'&&<Taste wineries={wineries} ratings={ratings} setRatings={setRatings} flash={flash}/>} 
   {tab==='friends'&&<Friends ratings={ratings}/>} 
   {tab==='profile'&&<Profile rated={rated} favorites={favorites}/>} 
  </main>
  <nav aria-label="Primary navigation">{[['discover',Map,'Explore'],['trip',Route,'Trip'],['taste',Wine,'Taste'],['friends',Users,'Friends'],['profile',UserRound,'You']].map(([id,I,label])=><button key={id} className={tab===id?'active':''} onClick={()=>go(id)} aria-current={tab===id?'page':undefined}><I size={21}/><span>{label}</span></button>)}</nav>
  {selected&&<Winery winery={selected} inTrip={trip.includes(selected.id)} addTrip={addTrip} ratings={ratings} setRatings={setRatings} close={()=>setSelected(null)} flash={flash}/>} 
  <InstallPrompt/>
  {toast&&<div className="toast"><Check size={18}/>{toast}</div>}
 </div>
}

function InstallPrompt(){const [show,setShow]=useState(false);const [deferred,setDeferred]=useState(null);const [ios,setIos]=useState(false);useEffect(()=>{if(localStorage.getItem('onesip-install-dismissed')||matchMedia('(display-mode: standalone)').matches)return;const isIos=/iphone|ipad|ipod/i.test(navigator.userAgent);setIos(isIos);const timer=setTimeout(()=>setShow(true),3500);const ready=e=>{e.preventDefault();setDeferred(e)};addEventListener('beforeinstallprompt',ready);return()=>{clearTimeout(timer);removeEventListener('beforeinstallprompt',ready)}},[]);const close=()=>{setShow(false);localStorage.setItem('onesip-install-dismissed','1')};const install=async()=>{if(deferred){await deferred.prompt();setShow(false)}else setIos(true)};if(!show)return null;return <div className="installBackdrop"><aside className="installCard" role="dialog" aria-modal="true" aria-labelledby="install-title"><button className="installClose" onClick={close} aria-label="Close"><X/></button><div className="appIcon">S</div><small>KEEP SIPS HANDY</small><h2 id="install-title">Save it to your Home Screen</h2><p>Open your journeys and rate wines like an app—no App Store needed.</p>{ios?<div className="iosSteps"><span><Share size={18}/> Tap <b>Share</b> in Safari</span><span><Plus size={18}/> Choose <b>Add to Home Screen</b></span></div>:<button className="installButton" onClick={install}><Download size={18}/> Save Sips</button>}<button className="later" onClick={close}>Maybe later</button></aside></div>}

function Discover({onOpen,trip,addTrip}){const [query,setQuery]=useState('');const [lake,setLake]=useState('All lakes');const shown=wineries.filter(w=>(lake==='All lakes'||w.lake===lake)&&(w.name+w.lake+w.tags.join('')).toLowerCase().includes(query.toLowerCase()));return <>
 <section className="hero"><img src="/finger-lakes-tasting.jpg"/><div className="heroShade"/><div className="heroCopy"><small>YOUR NEXT POUR</small><h1>Find the wines<br/>worth remembering.</h1><p>Plan together. Taste everything. Keep what you love.</p></div><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Winery, lake, or wine"/></div></section>
 <section className="section mapSection"><div className="titleRow"><div><small>EXPLORE {wineries.length-1} REGIONAL LISTINGS + 1 DEMO</small><h2>Finger Lakes wineries</h2></div><button className="textBtn">Map layers <ChevronRight size={16}/></button></div>
 <div className="lakeFilters" aria-label="Filter wineries by lake">{['All lakes',...lakes].map(x=><button className={lake===x?'active':''} onClick={()=>setLake(x)} key={x}>{x}</button>)}</div>
 <div className="mapCard"><div className="topo"></div><div className="lake l0"></div><div className="lake l1"></div><div className="lake l2"></div><div className="lake l3"></div><span className="lakeName n0">CANANDAIGUA</span><span className="lakeName n1">KEUKA</span><span className="lakeName n2">SENECA</span><span className="lakeName n3">CAYUGA</span>{shown.map(w=><button key={w.id} aria-label={`Open ${w.name}`} className="pin directoryPin" style={{left:w.x+'%',top:w.y+'%',background:w.color}} onClick={()=>onOpen(w)}><Wine size={12}/></button>)}<div className="mapHint"><Navigation size={15}/> {shown.length} wineries shown</div></div></section>
 <section className="section"><div className="titleRow"><div><small>REGIONAL DIRECTORY</small><h2>{lake==='All lakes'?'All wineries':lake}</h2></div><span className="resultCount">{shown.length} results</span></div><div className="cards">{shown.map(w=><article className="wineryCard" key={w.id} onClick={()=>onOpen(w)}><div className="cardTop"><span style={{background:w.color}}><Wine size={20}/></span><button aria-label={trip.includes(w.id)?`Remove ${w.name} from trip`:`Add ${w.name} to trip`} onClick={e=>{e.stopPropagation();addTrip(w.id)}} className={trip.includes(w.id)?'saved':''}>{trip.includes(w.id)?<Check/>:<Plus/>}</button></div><small>{w.lake}</small><h3>{w.name}</h3><div className="tags">{w.tags.map(x=><i key={x}>{x}</i>)}</div><div className="cardFoot"><b className="verifyDot">●</b><span>{w.verification}</span><ChevronRight/></div></article>)}</div></section>
 <section className="directorySource"><small>DIRECTORY SOURCE</small><p>Listings are seeded from the New York State winery-license directory. A license record does not guarantee a public tasting room; hours and visitor details are marked pending until verified.</p><a href="https://data.ny.gov/Economic-Development/new-york-wineries/tyci-urth" target="_blank" rel="noreferrer">View the source</a></section>
 <section className="deal"><Tag/><div><small>ONE SIP OFFER</small><h3>A bottle you loved, waiting at home.</h3><p>Rate a wine 5 and we’ll save it for future winery offers.</p></div><button>See how</button></section>
 </>}

function Trip({trip,ratings,onOpen}){const list=wineries.filter(w=>trip.includes(w.id));return <section className="page"><div className="pageHead"><small>OCTOBER 10–12</small><h1>Finger Lakes Weekend</h1><div className="people"><span>AC</span><span>JC</span><span>MK</span><button><Plus size={16}/></button><b>3 friends</b></div></div><div className="tripStats"><div><b>{list.length}</b><span>wineries</span></div><div><b>47 mi</b><span>planned</span></div><div><b>{Object.keys(ratings).length}</b><span>wines rated</span></div></div><div className="routeLine">{list.map((w,i)=><article key={w.id} onClick={()=>onOpen(w)}><div className="stop"><span>{i+1}</span>{i<list.length-1&&<i/>}</div><div><small>{i===0?'11:00 AM':'2:15 PM'} · {w.area}</small><h3>{w.name}</h3><p>{w.desc}</p><em>{w.wines.length} wines pouring</em></div><ChevronRight/></article>)}</div><button className="primary"><Share2 size={18}/> Invite friends to this trip</button></section>}

function Taste({wineries,ratings,setRatings,flash}){const w=wineries[0];return <section className="page"><div className="tasteHead"><small>INTERACTIVE DEMO · SAMPLE WINES</small><h1>{w.name}</h1><p>Tap a score for each of the {w.wines.length} wines in this sample flight.</p></div><RatingList winery={w} ratings={ratings} setRatings={setRatings} flash={flash}/></section>}

function RatingList({winery,ratings,setRatings,flash}){if(!winery.wines.length)return <div className="emptyTasting"><Wine/><h3>Tasting list coming soon</h3><p>This winery is in our reference directory. Current wines will be added after verification or winery participation.</p></div>;return <div className="wineList">{winery.wines.map(([name,type,price],idx)=>{const key=winery.id+'-'+idx;return <article key={name}><div className="wineInfo"><span>{idx+1}</span><div><small>{type} · {price}</small><h3>{name}</h3></div>{ratings[key]&&<b>{ratings[key]}</b>}</div><div className="rating">{scale.map((s,i)=><button title={s[1]} className={ratings[key]===i+1?'picked':''} onClick={()=>{setRatings(v=>({...v,[key]:i+1}));flash(i===4?'Saved to your anytime list':'Rating saved')}} key={s[0]}><strong>{i+1}</strong><span>{s[0]}</span></button>)}</div></article>})}</div>}

function Friends({ratings}){return <section className="page"><div className="friendsHero"><img src="/friends-wine-tasting.png" alt="Friends sharing a wine tasting overlooking a Finger Lakes vineyard"/><div><small>BETTER TOGETHER</small><h1>Turn every tasting into a shared story.</h1></div></div><div className="pageHead"><small>SHARED TASTING</small><h1>Your group agrees on the good stuff.</h1><p>Individual scores stay personal until everyone finishes the flight.</p></div><div className="consensus"><Sparkles/><small>GROUP FAVORITE</small><h2>2025 Dry Riesling</h2><p>Everyone would buy a bottle. Anthony and Jess rated it a 5.</p><div className="faceRow"><span>AC <b>5</b></span><span>JC <b>5</b></span><span>MK <b>3</b></span></div></div><h2 className="subhead">Trip leaderboard</h2>{['Dry Riesling','Cabernet Franc','Grüner Veltliner'].map((x,i)=><div className="leader" key={x}><b>{i+1}</b><div><strong>{x}</strong><span>{[4.7,4.3,3.9][i]} group score</span></div><div className="bar"><i style={{width:[94,86,78][i]+'%'}}/></div></div>)}<button className="primary"><Share2 size={18}/> Share trip recap</button></section>}

function Profile({rated,favorites}){return <section className="page"><div className="profileTop"><div className="bigAvatar">AC</div><small>YOUR CELLAR MEMORY</small><h1>Anthony</h1><p>Dry Riesling explorer · 3 Finger Lakes trips</p></div><div className="tripStats"><div><b>{rated||6}</b><span>wines tasted</span></div><div><b>{favorites.length||3}</b><span>favorites</span></div><div><b>7</b><span>wineries</span></div></div><div className="tasteDNA"><small>YOUR TASTE</small><h2>Bright, dry & cool-climate</h2><p>You consistently save dry Riesling, Cabernet Franc and mineral-driven whites.</p><div className="dna"><i style={{width:'88%'}}/><span>Dry</span><i style={{width:'72%'}}/><span>Acid</span><i style={{width:'43%'}}/><span>Body</span></div></div><div className="menu"><button><Heart/> Wines I’d order again <ChevronRight/></button><button><Route/> Past trips & maps <ChevronRight/></button><button><Store/> Wine club preview <ChevronRight/></button></div></section>}

function Winery({winery,inTrip,addTrip,ratings,setRatings,close,flash}){return <div className="overlay" onClick={close}><section className="sheet" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><div className="sheetHero" style={{background:`linear-gradient(135deg,${winery.color},#21141a)`}}><Wine/><small>{winery.lake} · {winery.area}</small><h2>{winery.name}</h2><div className="verificationBadge">{winery.verification}</div></div><div className="sheetBody"><p>{winery.desc}</p><div className="actions"><button className={inTrip?'added':''} onClick={()=>addTrip(winery.id)}>{inTrip?<Check/>:<Plus/>}{inTrip?'On your trip':'Add to trip'}</button><button disabled title="Available after address verification"><Navigation/>Directions soon</button></div><div className="titleRow"><div><small>TASTING INFORMATION</small><h2>Current wines</h2></div></div><RatingList winery={winery} ratings={ratings} setRatings={setRatings} flash={flash}/></div></section></div>}

createRoot(document.getElementById('root')).render(<App/>);
